import {
  ReadOutlined,
  SettingOutlined,
  SolutionOutlined,
} from "@ant-design/icons";
import { CategoryNewsEntity } from "../../common/services/category-news/categoryNews";
import {
  TreeNode,
} from "../../common/services/category/category";
import { NewsEntity } from "../../common/services/news/news";
import { QuestionEntity } from "../../common/services/question/question";
import { DocumentCategoriesEntity } from "../../common/services/document-categories/documentCategories";

export enum SIDE_BAR {
  LECTURE_VIDEO = "lecture-video",
  NEWS = "news",
  DEPARTMENT_MANAGEMENT = "department-management",
  USERS_MANAGEMENT = "users-management",
  ROLES_MANAGEMENT = "roles-management",
  PATIENTS_MANAGEMENT = "patients-management",
  MESSAGES_MANAGEMENT = "messages-management",
  LIST_REVIEWS = "list-reviews",
  DOCUMENT_CATEGORY = "document-category",
  DOCUMENT_MANAGEMENT = "document-management",
  DOCUMENT = "document",
  NEW_DETAIL = "new-detail",
}

export enum SUB_SYSTEM {
  CUSTOMER_SUPPORT = "CUSTOMER_SUPPORT",
  LIBRARY = "LIBRARY",
  MANAGEMENT = "MANAGEMENT",
}

export const environments = [
  {
    key: SUB_SYSTEM.CUSTOMER_SUPPORT,
    title: "Chăm sóc khách hàng",
    path: "/dashboard/customer-support",
    icon: <SolutionOutlined width={32} height={32} />,
  },
  {
    key: SUB_SYSTEM.LIBRARY,
    title: "Thư viện điện tử",
    path: "/dashboard/library",
    icon: <ReadOutlined width={32} height={32} />,
  },
  {
    key: SUB_SYSTEM.MANAGEMENT,
    title: "Quản trị hệ thống",
    path: "/dashboard/management",
    icon: <SettingOutlined width={32} height={32} />,
  },
];

export enum MEASSAGE {
  "SAVE" = "Lưu",
  "CREATE" = "Thêm",
  "CANCEL" = "Huỷ",
  "CLOSE" = "Đóng",
  "CONFIRM_DELETE" = "Xác nhận xóa",
  "OK" = "Có",
  "NO" = "Không",
  "DELETE_SUCCESS" = "Xóa thành công",
  "ERROR" = "Có lỗi xảy ra trong quá trình xử lý",
}

export const DEFAULT_PAGE_SIZE = 10;

export const buildCategoryTree = (
  categories: DocumentCategoriesEntity[],
  sidebar?: boolean,
  perDocumentCategories?: string[]
): TreeNode[] => {
  let filteredCategories = categories.filter((c) => {
    return sidebar
      ? c.parent_category_id !== 0 && c.status !== 0
      : c.id_category !== 1;
  });

  if (perDocumentCategories?.length) {
    filteredCategories = filteredCategories.filter((cate) => {
      return perDocumentCategories.includes(cate.id_category.toString());
    });
  }

  const categoryMap = new Map<number, TreeNode>();

  filteredCategories.forEach((category) => {
    categoryMap.set(category.id_category, {
      title: category.name,
      value: category.id_category.toString(),
      item: category,
      key: category.id_category.toString(),
      children: [],
    });
  });

  const tree: TreeNode[] = [];

  filteredCategories.forEach((category) => {
    const node = categoryMap.get(category.id_category)!;

    if (category.parent_category_id) {
      const parentNode = categoryMap.get(category.parent_category_id);
      if (parentNode) {
        parentNode.children!.push(node);
      } else {
        tree.push(node);
      }
    } else {
      tree.push(node);
    }
  });
  const cleanEmptyChildren = (nodes: TreeNode[]) => {
    nodes.forEach((node) => {
      if (node.children && node.children.length > 0) {
        cleanEmptyChildren(node.children);
      } else {
        delete node.children;
      }
    });
  };
  cleanEmptyChildren(tree);
  return tree;
};

export const listQuestions: QuestionEntity[] = [
  {
    id: "q1",
    order: 1,
    type: "CHOOSE",
    question:
      "Bệnh viện Quốc tế Sản Nhi Hải Phòng lắng nghe ý kiến của Quý khách và thay đổi để nâng cao chất lượng dịch vụ. Xin Quý khách vui lòng cho biết ý kiến của mình và điền đầy đủ, chính xác thông tin giúp chúng tôi có thể tiếp thu, phản hồi",
    options: [
      { label: "Đồng ý tham gia khảo sát", value: "yes", nextQuestionId: "q2" },
      { label: "Không đồng ý", value: "no", nextQuestionId: null },
    ],
    required: true,
  },
  {
    id: "q2",
    order: 2,
    type: "CHOOSE",
    question:
      "Quý khách có hài lòng khi khám chữa bệnh tại Bệnh viện Quốc tế Sản Nhi Hải Phòng không?",
    options: [
      { label: "Hài lòng", value: "yes", nextQuestionId: "q4" },
      { label: "Không hài lòng", value: "no", nextQuestionId: "q3" },
    ],
    required: true,
  },
  {
    id: "q3",
    order: 3,
    type: "TEXT",
    question:
      "Theo Quý khách, Bệnh viện Quốc tế Sản Nhi Hải Phòng cần cải thiện những dịch vụ gì để phục vụ tốt hơn nhu cầu khám chữa bệnh?",
    placeholder: "Vui lòng nhập tại đây",
    required: true,
    nextQuestionId: "q4",
  },
  {
    id: "q4",
    order: 4,
    type: "FORM",
    question: "Quý khách vui lòng nhập thông tin",
    required: true,
    formFields: [
      {
        name: "fullName",
        label: "Họ tên",
        type: "fullName",
        required: true,
        placeholder: "Nhập họ tên của bạn",
      },
      {
        name: "phone",
        label: "Số điện thoại",
        type: "phone",
        required: true,
        placeholder: "Nhập số điện thoại",
      },
      {
        name: "email",
        label: "Email",
        type: "email",
        required: false,
        placeholder: "Nhập email (nếu có)",
      },
    ],
  },
];

export const reviews = [
  {
    id: "1",
    name: "Nguyễn Thị A",
    phone: "0912345678",
    email: "nguyễn.thi.a@example.com",
    review: "Thái độ của nhân viên không thân thiện, trả lời cộc lốc.",
    created: "2025-07-01T08:00:00Z",
  },
  {
    id: "2",
    name: "Trần Văn B",
    phone: "0912345679",
    email: "trần.văn.b@example.com",
    review: "Chờ khám quá lâu, không có thông báo rõ ràng.",
    created: "2025-07-02T11:17:00Z",
  },
  {
    id: "3",
    name: "Lê Thị C",
    phone: "0912345680",
    email: "lê.thi.c@example.com",
    review: "Quy trình khám rườm rà, mất nhiều thời gian.",
    created: "2025-07-03T14:34:00Z",
  },
  {
    id: "4",
    name: "Phạm Văn D",
    phone: "0912345681",
    email: "pham.văn.d@example.com",
    review: "Bác sĩ khám rất sơ sài, không giải thích rõ tình trạng bệnh.",
    created: "2025-07-04T17:51:00Z",
  },
  {
    id: "5",
    name: "Hoàng Thị E",
    phone: "0912345682",
    email: "hoang.thi.e@example.com",
    review: "Phòng khám đông đúc, không đảm bảo vệ sinh.",
    created: "2025-07-05T10:08:00Z",
  },
  {
    id: "6",
    name: "Đỗ Văn F",
    phone: "0912345683",
    email: "dỗ.văn.f@example.com",
    review: "Chi phí cao nhưng chất lượng phục vụ không tương xứng.",
    created: "2025-07-06T13:25:00Z",
  },
  {
    id: "7",
    name: "Ngô Thị G",
    phone: "0912345684",
    email: "ngo.thi.g@example.com",
    review: "Lễ tân không hướng dẫn rõ ràng, gây khó khăn cho bệnh nhân mới.",
    created: "2025-07-07T16:42:00Z",
  },
  {
    id: "8",
    name: "Mai Văn H",
    phone: "0912345685",
    email: "mai.văn.h@example.com",
    review: "Bác sĩ khám qua loa, cảm giác không quan tâm đến người bệnh.",
    created: "2025-07-08T09:59:00Z",
  },
  {
    id: "9",
    name: "Lương Thị I",
    phone: "0912345686",
    email: "luong.thi.i@example.com",
    review: "Khám rồi vẫn không biết bệnh gì, không yên tâm chút nào.",
    created: "2025-07-09T12:16:00Z",
  },
  {
    id: "10",
    name: "Vũ Văn J",
    phone: "0912345687",
    email: "vu.văn.j@example.com",
    review: "Máy móc trục trặc, phải đợi sửa rất lâu mới được tiếp tục khám.",
    created: "2025-07-10T15:33:00Z",
  },
  {
    id: "11",
    name: "Nguyễn Văn K",
    phone: "0912345688",
    email: "nguyễn.văn.k@example.com",
    review: "Không có chỗ ngồi chờ, bệnh nhân phải đứng rất lâu.",
    created: "2025-07-11T08:50:00Z",
  },
  {
    id: "12",
    name: "Trịnh Thị L",
    phone: "0912345689",
    email: "trinh.thi.l@example.com",
    review: "Đăng ký online rồi mà vẫn phải chờ cả tiếng đồng hồ.",
    created: "2025-07-12T11:07:00Z",
  },
  {
    id: "13",
    name: "Lý Văn M",
    phone: "0912345690",
    email: "ly.văn.m@example.com",
    review: "Giá thuốc tại quầy cao hơn nhiều so với bên ngoài.",
    created: "2025-07-13T14:24:00Z",
  },
  {
    id: "14",
    name: "Đoàn Thị N",
    phone: "0912345691",
    email: "doan.thi.n@example.com",
    review: "Thái độ bác sĩ thiếu nhiệt tình, không trả lời câu hỏi rõ ràng.",
    created: "2025-07-14T17:41:00Z",
  },
  {
    id: "15",
    name: "Kiều Văn O",
    phone: "0912345692",
    email: "kiều.văn.o@example.com",
    review: "Hẹn tái khám nhưng đến nơi vẫn phải chờ lại từ đầu.",
    created: "2025-07-15T10:58:00Z",
  },
  {
    id: "16",
    name: "Bùi Thị P",
    phone: "0912345693",
    email: "bui.thi.p@example.com",
    review: "Nhân viên kỹ thuật làm việc chậm, thiếu trách nhiệm.",
    created: "2025-07-16T13:15:00Z",
  },
  {
    id: "17",
    name: "Tống Văn Q",
    phone: "0912345694",
    email: "tống.văn.q@example.com",
    review: "Không có người hướng dẫn trong khu vực khám, rất lộn xộn.",
    created: "2025-07-17T16:32:00Z",
  },
  {
    id: "18",
    name: "Phan Thị R",
    phone: "0912345695",
    email: "phan.thi.r@example.com",
    review: "Không khí phòng chờ quá nóng, không có điều hòa.",
    created: "2025-07-18T09:49:00Z",
  },
  {
    id: "19",
    name: "Nguyễn Văn S",
    phone: "0912345696",
    email: "nguyễn.văn.s@example.com",
    review: "Khâu thanh toán rườm rà, mất thời gian.",
    created: "2025-07-19T12:06:00Z",
  },
  {
    id: "20",
    name: "Võ Thị T",
    phone: "0912345697",
    email: "vo.thi.t@example.com",
    review: "Y tá gọi nhầm tên, gây nhầm lẫn giữa bệnh nhân.",
    created: "2025-07-20T15:23:00Z",
  },
  {
    id: "21",
    name: "Hồ Văn U",
    phone: "0912345698",
    email: "hồ.văn.u@example.com",
    review: "Quy trình xét nghiệm chậm, chờ kết quả quá lâu.",
    created: "2025-07-21T08:40:00Z",
  },
  {
    id: "22",
    name: "Trương Thị V",
    phone: "0912345699",
    email: "truong.thi.v@example.com",
    review: "Không có nơi để đồ cá nhân, rất bất tiện.",
    created: "2025-07-22T11:57:00Z",
  },
  {
    id: "23",
    name: "Đặng Văn W",
    phone: "0912345700",
    email: "dặng.văn.w@example.com",
    review:
      "Bác sĩ dùng từ chuyên môn quá nhiều, không giải thích cho người bệnh hiểu.",
    created: "2025-07-23T14:14:00Z",
  },
  {
    id: "24",
    name: "Cao Thị X",
    phone: "0912345701",
    email: "cao.thi.x@example.com",
    review: "Dịch vụ chăm sóc sau khám gần như không có.",
    created: "2025-07-24T17:31:00Z",
  },
  {
    id: "25",
    name: "Nguyễn Văn Y",
    phone: "0912345702",
    email: "nguyễn.văn.y@example.com",
    review: "Không hài lòng với cách xử lý phản ánh của bệnh viện.",
    created: "2025-07-25T10:48:00Z",
  },
  {
    id: "26",
    name: "Nguyễn Thị A",
    phone: "0912345703",
    email: "nguyễn.thi.a@example.com",
    review: "Thái độ của nhân viên không thân thiện, trả lời cộc lốc.",
    created: "2025-07-26T13:05:00Z",
  },
  {
    id: "27",
    name: "Trần Văn B",
    phone: "0912345704",
    email: "trần.văn.b@example.com",
    review: "Chờ khám quá lâu, không có thông báo rõ ràng.",
    created: "2025-07-27T16:22:00Z",
  },
  {
    id: "28",
    name: "Lê Thị C",
    phone: "0912345705",
    email: "lê.thi.c@example.com",
    review: "Quy trình khám rườm rà, mất nhiều thời gian.",
    created: "2025-07-28T09:39:00Z",
  },
  {
    id: "29",
    name: "Phạm Văn D",
    phone: "0912345706",
    email: "pham.văn.d@example.com",
    review: "Bác sĩ khám rất sơ sài, không giải thích rõ tình trạng bệnh.",
    created: "2025-07-29T12:56:00Z",
  },
  {
    id: "30",
    name: "Hoàng Thị E",
    phone: "0912345707",
    email: "hoang.thi.e@example.com",
    review: "Phòng khám đông đúc, không đảm bảo vệ sinh.",
    created: "2025-07-30T15:13:00Z",
  },
  {
    id: "31",
    name: "Đỗ Văn F",
    phone: "0912345708",
    email: "dỗ.văn.f@example.com",
    review: "Chi phí cao nhưng chất lượng phục vụ không tương xứng.",
    created: "2025-07-31T08:30:00Z",
  },
  {
    id: "32",
    name: "Ngô Thị G",
    phone: "0912345709",
    email: "ngo.thi.g@example.com",
    review: "Lễ tân không hướng dẫn rõ ràng, gây khó khăn cho bệnh nhân mới.",
    created: "2025-08-01T11:47:00Z",
  },
  {
    id: "33",
    name: "Mai Văn H",
    phone: "0912345710",
    email: "mai.văn.h@example.com",
    review: "Bác sĩ khám qua loa, cảm giác không quan tâm đến người bệnh.",
    created: "2025-08-02T14:04:00Z",
  },
  {
    id: "34",
    name: "Lương Thị I",
    phone: "0912345711",
    email: "luong.thi.i@example.com",
    review: "Khám rồi vẫn không biết bệnh gì, không yên tâm chút nào.",
    created: "2025-08-03T17:21:00Z",
  },
  {
    id: "35",
    name: "Vũ Văn J",
    phone: "0912345712",
    email: "vu.văn.j@example.com",
    review: "Máy móc trục trặc, phải đợi sửa rất lâu mới được tiếp tục khám.",
    created: "2025-08-04T10:38:00Z",
  },
  {
    id: "36",
    name: "Nguyễn Văn K",
    phone: "0912345713",
    email: "nguyễn.văn.k@example.com",
    review: "Không có chỗ ngồi chờ, bệnh nhân phải đứng rất lâu.",
    created: "2025-08-05T13:55:00Z",
  },
  {
    id: "37",
    name: "Trịnh Thị L",
    phone: "0912345714",
    email: "trinh.thi.l@example.com",
    review: "Đăng ký online rồi mà vẫn phải chờ cả tiếng đồng hồ.",
    created: "2025-08-06T16:12:00Z",
  },
  {
    id: "38",
    name: "Lý Văn M",
    phone: "0912345715",
    email: "ly.văn.m@example.com",
    review: "Giá thuốc tại quầy cao hơn nhiều so với bên ngoài.",
    created: "2025-08-07T09:29:00Z",
  },
  {
    id: "39",
    name: "Đoàn Thị N",
    phone: "0912345716",
    email: "doan.thi.n@example.com",
    review: "Thái độ bác sĩ thiếu nhiệt tình, không trả lời câu hỏi rõ ràng.",
    created: "2025-08-08T12:46:00Z",
  },
  {
    id: "40",
    name: "Kiều Văn O",
    phone: "0912345717",
    email: "kiều.văn.o@example.com",
    review: "Hẹn tái khám nhưng đến nơi vẫn phải chờ lại từ đầu.",
    created: "2025-08-09T15:03:00Z",
  },
  {
    id: "41",
    name: "Bùi Thị P",
    phone: "0912345718",
    email: "bui.thi.p@example.com",
    review: "Nhân viên kỹ thuật làm việc chậm, thiếu trách nhiệm.",
    created: "2025-08-10T08:20:00Z",
  },
  {
    id: "42",
    name: "Tống Văn Q",
    phone: "0912345719",
    email: "tống.văn.q@example.com",
    review: "Không có người hướng dẫn trong khu vực khám, rất lộn xộn.",
    created: "2025-08-11T11:37:00Z",
  },
  {
    id: "43",
    name: "Phan Thị R",
    phone: "0912345720",
    email: "phan.thi.r@example.com",
    review: "Không khí phòng chờ quá nóng, không có điều hòa.",
    created: "2025-08-12T14:54:00Z",
  },
  {
    id: "44",
    name: "Nguyễn Văn S",
    phone: "0912345721",
    email: "nguyễn.văn.s@example.com",
    review: "Khâu thanh toán rườm rà, mất thời gian.",
    created: "2025-08-13T17:11:00Z",
  },
  {
    id: "45",
    name: "Võ Thị T",
    phone: "0912345722",
    email: "vo.thi.t@example.com",
    review: "Y tá gọi nhầm tên, gây nhầm lẫn giữa bệnh nhân.",
    created: "2025-08-14T10:28:00Z",
  },
  {
    id: "46",
    name: "Hồ Văn U",
    phone: "0912345723",
    email: "hồ.văn.u@example.com",
    review: "Quy trình xét nghiệm chậm, chờ kết quả quá lâu.",
    created: "2025-08-15T13:45:00Z",
  },
  {
    id: "47",
    name: "Trương Thị V",
    phone: "0912345724",
    email: "truong.thi.v@example.com",
    review: "Không có nơi để đồ cá nhân, rất bất tiện.",
    created: "2025-07-01T16:02:00Z",
  },
  {
    id: "48",
    name: "Đặng Văn W",
    phone: "0912345725",
    email: "dặng.văn.w@example.com",
    review:
      "Bác sĩ dùng từ chuyên môn quá nhiều, không giải thích cho người bệnh hiểu.",
    created: "2025-07-02T09:19:00Z",
  },
  {
    id: "49",
    name: "Cao Thị X",
    phone: "0912345726",
    email: "cao.thi.x@example.com",
    review: "Dịch vụ chăm sóc sau khám gần như không có.",
    created: "2025-07-03T12:36:00Z",
  },
  {
    id: "50",
    name: "Nguyễn Văn Y",
    phone: "0912345727",
    email: "nguyễn.văn.y@example.com",
    review: "Không hài lòng với cách xử lý phản ánh của bệnh viện.",
    created: "2025-07-04T15:53:00Z",
  },
  {
    id: "51",
    name: "Nguyễn Thị A",
    phone: "0912345728",
    email: "nguyễn.thi.a@example.com",
    review: "Thái độ của nhân viên không thân thiện, trả lời cộc lốc.",
    created: "2025-07-05T08:10:00Z",
  },
  {
    id: "52",
    name: "Trần Văn B",
    phone: "0912345729",
    email: "trần.văn.b@example.com",
    review: "Chờ khám quá lâu, không có thông báo rõ ràng.",
    created: "2025-07-06T11:27:00Z",
  },
  {
    id: "53",
    name: "Lê Thị C",
    phone: "0912345730",
    email: "lê.thi.c@example.com",
    review: "Quy trình khám rườm rà, mất nhiều thời gian.",
    created: "2025-07-07T14:44:00Z",
  },
  {
    id: "54",
    name: "Phạm Văn D",
    phone: "0912345731",
    email: "pham.văn.d@example.com",
    review: "Bác sĩ khám rất sơ sài, không giải thích rõ tình trạng bệnh.",
    created: "2025-07-08T17:01:00Z",
  },
  {
    id: "55",
    name: "Hoàng Thị E",
    phone: "0912345732",
    email: "hoang.thi.e@example.com",
    review: "Phòng khám đông đúc, không đảm bảo vệ sinh.",
    created: "2025-07-09T10:18:00Z",
  },
  {
    id: "56",
    name: "Đỗ Văn F",
    phone: "0912345733",
    email: "dỗ.văn.f@example.com",
    review: "Chi phí cao nhưng chất lượng phục vụ không tương xứng.",
    created: "2025-07-10T13:35:00Z",
  },
  {
    id: "57",
    name: "Ngô Thị G",
    phone: "0912345734",
    email: "ngo.thi.g@example.com",
    review: "Lễ tân không hướng dẫn rõ ràng, gây khó khăn cho bệnh nhân mới.",
    created: "2025-07-11T16:52:00Z",
  },
  {
    id: "58",
    name: "Mai Văn H",
    phone: "0912345735",
    email: "mai.văn.h@example.com",
    review: "Bác sĩ khám qua loa, cảm giác không quan tâm đến người bệnh.",
    created: "2025-07-12T09:09:00Z",
  },
  {
    id: "59",
    name: "Lương Thị I",
    phone: "0912345736",
    email: "luong.thi.i@example.com",
    review: "Khám rồi vẫn không biết bệnh gì, không yên tâm chút nào.",
    created: "2025-07-13T12:26:00Z",
  },
  {
    id: "60",
    name: "Vũ Văn J",
    phone: "0912345737",
    email: "vu.văn.j@example.com",
    review: "Máy móc trục trặc, phải đợi sửa rất lâu mới được tiếp tục khám.",
    created: "2025-07-14T15:43:00Z",
  },
  {
    id: "61",
    name: "Nguyễn Văn K",
    phone: "0912345738",
    email: "nguyễn.văn.k@example.com",
    review: "Không có chỗ ngồi chờ, bệnh nhân phải đứng rất lâu.",
    created: "2025-07-15T08:00:00Z",
  },
  {
    id: "62",
    name: "Trịnh Thị L",
    phone: "0912345739",
    email: "trinh.thi.l@example.com",
    review: "Đăng ký online rồi mà vẫn phải chờ cả tiếng đồng hồ.",
    created: "2025-07-16T11:17:00Z",
  },
  {
    id: "63",
    name: "Lý Văn M",
    phone: "0912345740",
    email: "ly.văn.m@example.com",
    review: "Giá thuốc tại quầy cao hơn nhiều so với bên ngoài.",
    created: "2025-07-17T14:34:00Z",
  },
  {
    id: "64",
    name: "Đoàn Thị N",
    phone: "0912345741",
    email: "doan.thi.n@example.com",
    review: "Thái độ bác sĩ thiếu nhiệt tình, không trả lời câu hỏi rõ ràng.",
    created: "2025-07-18T17:51:00Z",
  },
  {
    id: "65",
    name: "Kiều Văn O",
    phone: "0912345742",
    email: "kiều.văn.o@example.com",
    review: "Hẹn tái khám nhưng đến nơi vẫn phải chờ lại từ đầu.",
    created: "2025-07-19T10:08:00Z",
  },
  {
    id: "66",
    name: "Bùi Thị P",
    phone: "0912345743",
    email: "bui.thi.p@example.com",
    review: "Nhân viên kỹ thuật làm việc chậm, thiếu trách nhiệm.",
    created: "2025-07-20T13:25:00Z",
  },
  {
    id: "67",
    name: "Tống Văn Q",
    phone: "0912345744",
    email: "tống.văn.q@example.com",
    review: "Không có người hướng dẫn trong khu vực khám, rất lộn xộn.",
    created: "2025-07-21T16:42:00Z",
  },
  {
    id: "68",
    name: "Phan Thị R",
    phone: "0912345745",
    email: "phan.thi.r@example.com",
    review: "Không khí phòng chờ quá nóng, không có điều hòa.",
    created: "2025-07-22T09:59:00Z",
  },
  {
    id: "69",
    name: "Nguyễn Văn S",
    phone: "0912345746",
    email: "nguyễn.văn.s@example.com",
    review: "Khâu thanh toán rườm rà, mất thời gian.",
    created: "2025-07-23T12:16:00Z",
  },
  {
    id: "70",
    name: "Võ Thị T",
    phone: "0912345747",
    email: "vo.thi.t@example.com",
    review: "Y tá gọi nhầm tên, gây nhầm lẫn giữa bệnh nhân.",
    created: "2025-07-24T15:33:00Z",
  },
  {
    id: "71",
    name: "Hồ Văn U",
    phone: "0912345748",
    email: "hồ.văn.u@example.com",
    review: "Quy trình xét nghiệm chậm, chờ kết quả quá lâu.",
    created: "2025-07-25T08:50:00Z",
  },
  {
    id: "72",
    name: "Trương Thị V",
    phone: "0912345749",
    email: "truong.thi.v@example.com",
    review: "Không có nơi để đồ cá nhân, rất bất tiện.",
    created: "2025-07-26T11:07:00Z",
  },
  {
    id: "73",
    name: "Đặng Văn W",
    phone: "0912345750",
    email: "dặng.văn.w@example.com",
    review:
      "Bác sĩ dùng từ chuyên môn quá nhiều, không giải thích cho người bệnh hiểu.",
    created: "2025-07-27T14:24:00Z",
  },
  {
    id: "74",
    name: "Cao Thị X",
    phone: "0912345751",
    email: "cao.thi.x@example.com",
    review: "Dịch vụ chăm sóc sau khám gần như không có.",
    created: "2025-07-28T17:41:00Z",
  },
  {
    id: "75",
    name: "Nguyễn Văn Y",
    phone: "0912345752",
    email: "nguyễn.văn.y@example.com",
    review: "Không hài lòng với cách xử lý phản ánh của bệnh viện.",
    created: "2025-07-29T10:58:00Z",
  },
  {
    id: "76",
    name: "Nguyễn Thị A",
    phone: "0912345753",
    email: "nguyễn.thi.a@example.com",
    review: "Thái độ của nhân viên không thân thiện, trả lời cộc lốc.",
    created: "2025-07-30T13:15:00Z",
  },
  {
    id: "77",
    name: "Trần Văn B",
    phone: "0912345754",
    email: "trần.văn.b@example.com",
    review: "Chờ khám quá lâu, không có thông báo rõ ràng.",
    created: "2025-07-31T16:32:00Z",
  },
  {
    id: "78",
    name: "Lê Thị C",
    phone: "0912345755",
    email: "lê.thi.c@example.com",
    review: "Quy trình khám rườm rà, mất nhiều thời gian.",
    created: "2025-08-01T09:49:00Z",
  },
  {
    id: "79",
    name: "Phạm Văn D",
    phone: "0912345756",
    email: "pham.văn.d@example.com",
    review: "Bác sĩ khám rất sơ sài, không giải thích rõ tình trạng bệnh.",
    created: "2025-08-02T12:06:00Z",
  },
  {
    id: "80",
    name: "Hoàng Thị E",
    phone: "0912345757",
    email: "hoang.thi.e@example.com",
    review: "Phòng khám đông đúc, không đảm bảo vệ sinh.",
    created: "2025-08-03T15:23:00Z",
  },
  {
    id: "81",
    name: "Đỗ Văn F",
    phone: "0912345758",
    email: "dỗ.văn.f@example.com",
    review: "Chi phí cao nhưng chất lượng phục vụ không tương xứng.",
    created: "2025-08-04T08:40:00Z",
  },
  {
    id: "82",
    name: "Ngô Thị G",
    phone: "0912345759",
    email: "ngo.thi.g@example.com",
    review: "Lễ tân không hướng dẫn rõ ràng, gây khó khăn cho bệnh nhân mới.",
    created: "2025-08-05T11:57:00Z",
  },
  {
    id: "83",
    name: "Mai Văn H",
    phone: "0912345760",
    email: "mai.văn.h@example.com",
    review: "Bác sĩ khám qua loa, cảm giác không quan tâm đến người bệnh.",
    created: "2025-08-06T14:14:00Z",
  },
  {
    id: "84",
    name: "Lương Thị I",
    phone: "0912345761",
    email: "luong.thi.i@example.com",
    review: "Khám rồi vẫn không biết bệnh gì, không yên tâm chút nào.",
    created: "2025-08-07T17:31:00Z",
  },
  {
    id: "85",
    name: "Vũ Văn J",
    phone: "0912345762",
    email: "vu.văn.j@example.com",
    review: "Máy móc trục trặc, phải đợi sửa rất lâu mới được tiếp tục khám.",
    created: "2025-08-08T10:48:00Z",
  },
  {
    id: "86",
    name: "Nguyễn Văn K",
    phone: "0912345763",
    email: "nguyễn.văn.k@example.com",
    review: "Không có chỗ ngồi chờ, bệnh nhân phải đứng rất lâu.",
    created: "2025-08-09T13:05:00Z",
  },
  {
    id: "87",
    name: "Trịnh Thị L",
    phone: "0912345764",
    email: "trinh.thi.l@example.com",
    review: "Đăng ký online rồi mà vẫn phải chờ cả tiếng đồng hồ.",
    created: "2025-08-10T16:22:00Z",
  },
  {
    id: "88",
    name: "Lý Văn M",
    phone: "0912345765",
    email: "ly.văn.m@example.com",
    review: "Giá thuốc tại quầy cao hơn nhiều so với bên ngoài.",
    created: "2025-08-11T09:39:00Z",
  },
  {
    id: "89",
    name: "Đoàn Thị N",
    phone: "0912345766",
    email: "doan.thi.n@example.com",
    review: "Thái độ bác sĩ thiếu nhiệt tình, không trả lời câu hỏi rõ ràng.",
    created: "2025-08-12T12:56:00Z",
  },
  {
    id: "90",
    name: "Kiều Văn O",
    phone: "0912345767",
    email: "kiều.văn.o@example.com",
    review: "Hẹn tái khám nhưng đến nơi vẫn phải chờ lại từ đầu.",
    created: "2025-08-13T15:13:00Z",
  },
  {
    id: "91",
    name: "Bùi Thị P",
    phone: "0912345768",
    email: "bui.thi.p@example.com",
    review: "Nhân viên kỹ thuật làm việc chậm, thiếu trách nhiệm.",
    created: "2025-08-14T08:30:00Z",
  },
  {
    id: "92",
    name: "Tống Văn Q",
    phone: "0912345769",
    email: "tống.văn.q@example.com",
    review: "Không có người hướng dẫn trong khu vực khám, rất lộn xộn.",
    created: "2025-08-15T11:47:00Z",
  },
  {
    id: "93",
    name: "Phan Thị R",
    phone: "0912345770",
    email: "phan.thi.r@example.com",
    review: "Không khí phòng chờ quá nóng, không có điều hòa.",
    created: "2025-07-01T14:04:00Z",
  },
  {
    id: "94",
    name: "Nguyễn Văn S",
    phone: "0912345771",
    email: "nguyễn.văn.s@example.com",
    review: "Khâu thanh toán rườm rà, mất thời gian.",
    created: "2025-07-02T17:21:00Z",
  },
  {
    id: "95",
    name: "Võ Thị T",
    phone: "0912345772",
    email: "vo.thi.t@example.com",
    review: "Y tá gọi nhầm tên, gây nhầm lẫn giữa bệnh nhân.",
    created: "2025-07-03T10:38:00Z",
  },
  {
    id: "96",
    name: "Hồ Văn U",
    phone: "0912345773",
    email: "hồ.văn.u@example.com",
    review: "Quy trình xét nghiệm chậm, chờ kết quả quá lâu.",
    created: "2025-07-04T13:55:00Z",
  },
  {
    id: "97",
    name: "Trương Thị V",
    phone: "0912345774",
    email: "truong.thi.v@example.com",
    review: "Không có nơi để đồ cá nhân, rất bất tiện.",
    created: "2025-07-05T16:12:00Z",
  },
  {
    id: "98",
    name: "Đặng Văn W",
    phone: "0912345775",
    email: "dặng.văn.w@example.com",
    review:
      "Bác sĩ dùng từ chuyên môn quá nhiều, không giải thích cho người bệnh hiểu.",
    created: "2025-07-06T09:29:00Z",
  },
  {
    id: "99",
    name: "Cao Thị X",
    phone: "0912345776",
    email: "cao.thi.x@example.com",
    review: "Dịch vụ chăm sóc sau khám gần như không có.",
    created: "2025-07-07T12:46:00Z",
  },
  {
    id: "100",
    name: "Nguyễn Văn Y",
    phone: "0912345777",
    email: "nguyễn.văn.y@example.com",
    review: "Không hài lòng với cách xử lý phản ánh của bệnh viện.",
    created: "2025-07-08T15:03:00Z",
  },
  {
    id: "101",
    name: "Nguyễn Thị A",
    phone: "0912345778",
    email: "nguyễn.thi.a@example.com",
    review: "Thái độ của nhân viên không thân thiện, trả lời cộc lốc.",
    created: "2025-07-09T08:20:00Z",
  },
  {
    id: "102",
    name: "Trần Văn B",
    phone: "0912345779",
    email: "trần.văn.b@example.com",
    review: "Chờ khám quá lâu, không có thông báo rõ ràng.",
    created: "2025-07-10T11:37:00Z",
  },
  {
    id: "103",
    name: "Lê Thị C",
    phone: "0912345780",
    email: "lê.thi.c@example.com",
    review: "Quy trình khám rườm rà, mất nhiều thời gian.",
    created: "2025-07-11T14:54:00Z",
  },
  {
    id: "104",
    name: "Phạm Văn D",
    phone: "0912345781",
    email: "pham.văn.d@example.com",
    review: "Bác sĩ khám rất sơ sài, không giải thích rõ tình trạng bệnh.",
    created: "2025-07-12T17:11:00Z",
  },
  {
    id: "105",
    name: "Hoàng Thị E",
    phone: "0912345782",
    email: "hoang.thi.e@example.com",
    review: "Phòng khám đông đúc, không đảm bảo vệ sinh.",
    created: "2025-07-13T10:28:00Z",
  },
  {
    id: "106",
    name: "Đỗ Văn F",
    phone: "0912345783",
    email: "dỗ.văn.f@example.com",
    review: "Chi phí cao nhưng chất lượng phục vụ không tương xứng.",
    created: "2025-07-14T13:45:00Z",
  },
  {
    id: "107",
    name: "Ngô Thị G",
    phone: "0912345784",
    email: "ngo.thi.g@example.com",
    review: "Lễ tân không hướng dẫn rõ ràng, gây khó khăn cho bệnh nhân mới.",
    created: "2025-07-15T16:02:00Z",
  },
  {
    id: "108",
    name: "Mai Văn H",
    phone: "0912345785",
    email: "mai.văn.h@example.com",
    review: "Bác sĩ khám qua loa, cảm giác không quan tâm đến người bệnh.",
    created: "2025-07-16T09:19:00Z",
  },
  {
    id: "109",
    name: "Lương Thị I",
    phone: "0912345786",
    email: "luong.thi.i@example.com",
    review: "Khám rồi vẫn không biết bệnh gì, không yên tâm chút nào.",
    created: "2025-07-17T12:36:00Z",
  },
  {
    id: "110",
    name: "Vũ Văn J",
    phone: "0912345787",
    email: "vu.văn.j@example.com",
    review: "Máy móc trục trặc, phải đợi sửa rất lâu mới được tiếp tục khám.",
    created: "2025-07-18T15:53:00Z",
  },
  {
    id: "111",
    name: "Nguyễn Văn K",
    phone: "0912345788",
    email: "nguyễn.văn.k@example.com",
    review: "Không có chỗ ngồi chờ, bệnh nhân phải đứng rất lâu.",
    created: "2025-07-19T08:10:00Z",
  },
  {
    id: "112",
    name: "Trịnh Thị L",
    phone: "0912345789",
    email: "trinh.thi.l@example.com",
    review: "Đăng ký online rồi mà vẫn phải chờ cả tiếng đồng hồ.",
    created: "2025-07-20T11:27:00Z",
  },
  {
    id: "113",
    name: "Lý Văn M",
    phone: "0912345790",
    email: "ly.văn.m@example.com",
    review: "Giá thuốc tại quầy cao hơn nhiều so với bên ngoài.",
    created: "2025-07-21T14:44:00Z",
  },
  {
    id: "114",
    name: "Đoàn Thị N",
    phone: "0912345791",
    email: "doan.thi.n@example.com",
    review: "Thái độ bác sĩ thiếu nhiệt tình, không trả lời câu hỏi rõ ràng.",
    created: "2025-07-22T17:01:00Z",
  },
  {
    id: "115",
    name: "Kiều Văn O",
    phone: "0912345792",
    email: "kiều.văn.o@example.com",
    review: "Hẹn tái khám nhưng đến nơi vẫn phải chờ lại từ đầu.",
    created: "2025-07-23T10:18:00Z",
  },
  {
    id: "116",
    name: "Bùi Thị P",
    phone: "0912345793",
    email: "bui.thi.p@example.com",
    review: "Nhân viên kỹ thuật làm việc chậm, thiếu trách nhiệm.",
    created: "2025-07-24T13:35:00Z",
  },
  {
    id: "117",
    name: "Tống Văn Q",
    phone: "0912345794",
    email: "tống.văn.q@example.com",
    review: "Không có người hướng dẫn trong khu vực khám, rất lộn xộn.",
    created: "2025-07-25T16:52:00Z",
  },
  {
    id: "118",
    name: "Phan Thị R",
    phone: "0912345795",
    email: "phan.thi.r@example.com",
    review: "Không khí phòng chờ quá nóng, không có điều hòa.",
    created: "2025-07-26T09:09:00Z",
  },
  {
    id: "119",
    name: "Nguyễn Văn S",
    phone: "0912345796",
    email: "nguyễn.văn.s@example.com",
    review: "Khâu thanh toán rườm rà, mất thời gian.",
    created: "2025-07-27T12:26:00Z",
  },
  {
    id: "120",
    name: "Võ Thị T",
    phone: "0912345797",
    email: "vo.thi.t@example.com",
    review: "Y tá gọi nhầm tên, gây nhầm lẫn giữa bệnh nhân.",
    created: "2025-07-28T15:43:00Z",
  },
  {
    id: "121",
    name: "Hồ Văn U",
    phone: "0912345798",
    email: "hồ.văn.u@example.com",
    review: "Quy trình xét nghiệm chậm, chờ kết quả quá lâu.",
    created: "2025-07-29T08:00:00Z",
  },
  {
    id: "122",
    name: "Trương Thị V",
    phone: "0912345799",
    email: "truong.thi.v@example.com",
    review: "Không có nơi để đồ cá nhân, rất bất tiện.",
    created: "2025-07-30T11:17:00Z",
  },
  {
    id: "123",
    name: "Đặng Văn W",
    phone: "0912345800",
    email: "dặng.văn.w@example.com",
    review:
      "Bác sĩ dùng từ chuyên môn quá nhiều, không giải thích cho người bệnh hiểu.",
    created: "2025-07-31T14:34:00Z",
  },
  {
    id: "124",
    name: "Cao Thị X",
    phone: "0912345801",
    email: "cao.thi.x@example.com",
    review: "Dịch vụ chăm sóc sau khám gần như không có.",
    created: "2025-08-01T17:51:00Z",
  },
  {
    id: "125",
    name: "Nguyễn Văn Y",
    phone: "0912345802",
    email: "nguyễn.văn.y@example.com",
    review: "Không hài lòng với cách xử lý phản ánh của bệnh viện.",
    created: "2025-08-02T10:08:00Z",
  },
  {
    id: "126",
    name: "Nguyễn Thị A",
    phone: "0912345803",
    email: "nguyễn.thi.a@example.com",
    review: "Thái độ của nhân viên không thân thiện, trả lời cộc lốc.",
    created: "2025-08-03T13:25:00Z",
  },
  {
    id: "127",
    name: "Trần Văn B",
    phone: "0912345804",
    email: "trần.văn.b@example.com",
    review: "Chờ khám quá lâu, không có thông báo rõ ràng.",
    created: "2025-08-04T16:42:00Z",
  },
  {
    id: "128",
    name: "Lê Thị C",
    phone: "0912345805",
    email: "lê.thi.c@example.com",
    review: "Quy trình khám rườm rà, mất nhiều thời gian.",
    created: "2025-08-05T09:59:00Z",
  },
  {
    id: "129",
    name: "Phạm Văn D",
    phone: "0912345806",
    email: "pham.văn.d@example.com",
    review: "Bác sĩ khám rất sơ sài, không giải thích rõ tình trạng bệnh.",
    created: "2025-08-06T12:16:00Z",
  },
  {
    id: "130",
    name: "Hoàng Thị E",
    phone: "0912345807",
    email: "hoang.thi.e@example.com",
    review: "Phòng khám đông đúc, không đảm bảo vệ sinh.",
    created: "2025-08-07T15:33:00Z",
  },
  {
    id: "131",
    name: "Đỗ Văn F",
    phone: "0912345808",
    email: "dỗ.văn.f@example.com",
    review: "Chi phí cao nhưng chất lượng phục vụ không tương xứng.",
    created: "2025-08-08T08:50:00Z",
  },
  {
    id: "132",
    name: "Ngô Thị G",
    phone: "0912345809",
    email: "ngo.thi.g@example.com",
    review: "Lễ tân không hướng dẫn rõ ràng, gây khó khăn cho bệnh nhân mới.",
    created: "2025-08-09T11:07:00Z",
  },
  {
    id: "133",
    name: "Mai Văn H",
    phone: "0912345810",
    email: "mai.văn.h@example.com",
    review: "Bác sĩ khám qua loa, cảm giác không quan tâm đến người bệnh.",
    created: "2025-08-10T14:24:00Z",
  },
  {
    id: "134",
    name: "Lương Thị I",
    phone: "0912345811",
    email: "luong.thi.i@example.com",
    review: "Khám rồi vẫn không biết bệnh gì, không yên tâm chút nào.",
    created: "2025-08-11T17:41:00Z",
  },
  {
    id: "135",
    name: "Vũ Văn J",
    phone: "0912345812",
    email: "vu.văn.j@example.com",
    review: "Máy móc trục trặc, phải đợi sửa rất lâu mới được tiếp tục khám.",
    created: "2025-08-12T10:58:00Z",
  },
  {
    id: "136",
    name: "Nguyễn Văn K",
    phone: "0912345813",
    email: "nguyễn.văn.k@example.com",
    review: "Không có chỗ ngồi chờ, bệnh nhân phải đứng rất lâu.",
    created: "2025-08-13T13:15:00Z",
  },
  {
    id: "137",
    name: "Trịnh Thị L",
    phone: "0912345814",
    email: "trinh.thi.l@example.com",
    review: "Đăng ký online rồi mà vẫn phải chờ cả tiếng đồng hồ.",
    created: "2025-08-14T16:32:00Z",
  },
  {
    id: "138",
    name: "Lý Văn M",
    phone: "0912345815",
    email: "ly.văn.m@example.com",
    review: "Giá thuốc tại quầy cao hơn nhiều so với bên ngoài.",
    created: "2025-08-15T09:49:00Z",
  },
  {
    id: "139",
    name: "Đoàn Thị N",
    phone: "0912345816",
    email: "doan.thi.n@example.com",
    review: "Thái độ bác sĩ thiếu nhiệt tình, không trả lời câu hỏi rõ ràng.",
    created: "2025-07-01T12:06:00Z",
  },
  {
    id: "140",
    name: "Kiều Văn O",
    phone: "0912345817",
    email: "kiều.văn.o@example.com",
    review: "Hẹn tái khám nhưng đến nơi vẫn phải chờ lại từ đầu.",
    created: "2025-07-02T15:23:00Z",
  },
  {
    id: "141",
    name: "Bùi Thị P",
    phone: "0912345818",
    email: "bui.thi.p@example.com",
    review: "Nhân viên kỹ thuật làm việc chậm, thiếu trách nhiệm.",
    created: "2025-07-03T08:40:00Z",
  },
  {
    id: "142",
    name: "Tống Văn Q",
    phone: "0912345819",
    email: "tống.văn.q@example.com",
    review: "Không có người hướng dẫn trong khu vực khám, rất lộn xộn.",
    created: "2025-07-04T11:57:00Z",
  },
  {
    id: "143",
    name: "Phan Thị R",
    phone: "0912345820",
    email: "phan.thi.r@example.com",
    review: "Không khí phòng chờ quá nóng, không có điều hòa.",
    created: "2025-07-05T14:14:00Z",
  },
  {
    id: "144",
    name: "Nguyễn Văn S",
    phone: "0912345821",
    email: "nguyễn.văn.s@example.com",
    review: "Khâu thanh toán rườm rà, mất thời gian.",
    created: "2025-07-06T17:31:00Z",
  },
  {
    id: "145",
    name: "Võ Thị T",
    phone: "0912345822",
    email: "vo.thi.t@example.com",
    review: "Y tá gọi nhầm tên, gây nhầm lẫn giữa bệnh nhân.",
    created: "2025-07-07T10:48:00Z",
  },
  {
    id: "146",
    name: "Hồ Văn U",
    phone: "0912345823",
    email: "hồ.văn.u@example.com",
    review: "Quy trình xét nghiệm chậm, chờ kết quả quá lâu.",
    created: "2025-07-08T13:05:00Z",
  },
  {
    id: "147",
    name: "Trương Thị V",
    phone: "0912345824",
    email: "truong.thi.v@example.com",
    review: "Không có nơi để đồ cá nhân, rất bất tiện.",
    created: "2025-07-09T16:22:00Z",
  },
  {
    id: "148",
    name: "Đặng Văn W",
    phone: "0912345825",
    email: "dặng.văn.w@example.com",
    review:
      "Bác sĩ dùng từ chuyên môn quá nhiều, không giải thích cho người bệnh hiểu.",
    created: "2025-07-10T09:39:00Z",
  },
  {
    id: "149",
    name: "Cao Thị X",
    phone: "0912345826",
    email: "cao.thi.x@example.com",
    review: "Dịch vụ chăm sóc sau khám gần như không có.",
    created: "2025-07-11T12:56:00Z",
  },
  {
    id: "150",
    name: "Nguyễn Văn Y",
    phone: "0912345827",
    email: "nguyễn.văn.y@example.com",
    review: "Không hài lòng với cách xử lý phản ánh của bệnh viện.",
    created: "2025-07-12T15:13:00Z",
  },
  {
    id: "151",
    name: "Nguyễn Thị A",
    phone: "0912345828",
    email: "nguyễn.thi.a@example.com",
    review: "Thái độ của nhân viên không thân thiện, trả lời cộc lốc.",
    created: "2025-07-13T08:30:00Z",
  },
  {
    id: "152",
    name: "Trần Văn B",
    phone: "0912345829",
    email: "trần.văn.b@example.com",
    review: "Chờ khám quá lâu, không có thông báo rõ ràng.",
    created: "2025-07-14T11:47:00Z",
  },
  {
    id: "153",
    name: "Lê Thị C",
    phone: "0912345830",
    email: "lê.thi.c@example.com",
    review: "Quy trình khám rườm rà, mất nhiều thời gian.",
    created: "2025-07-15T14:04:00Z",
  },
  {
    id: "154",
    name: "Phạm Văn D",
    phone: "0912345831",
    email: "pham.văn.d@example.com",
    review: "Bác sĩ khám rất sơ sài, không giải thích rõ tình trạng bệnh.",
    created: "2025-07-16T17:21:00Z",
  },
  {
    id: "155",
    name: "Hoàng Thị E",
    phone: "0912345832",
    email: "hoang.thi.e@example.com",
    review: "Phòng khám đông đúc, không đảm bảo vệ sinh.",
    created: "2025-07-17T10:38:00Z",
  },
  {
    id: "156",
    name: "Đỗ Văn F",
    phone: "0912345833",
    email: "dỗ.văn.f@example.com",
    review: "Chi phí cao nhưng chất lượng phục vụ không tương xứng.",
    created: "2025-07-18T13:55:00Z",
  },
  {
    id: "157",
    name: "Ngô Thị G",
    phone: "0912345834",
    email: "ngo.thi.g@example.com",
    review: "Lễ tân không hướng dẫn rõ ràng, gây khó khăn cho bệnh nhân mới.",
    created: "2025-07-19T16:12:00Z",
  },
  {
    id: "158",
    name: "Mai Văn H",
    phone: "0912345835",
    email: "mai.văn.h@example.com",
    review: "Bác sĩ khám qua loa, cảm giác không quan tâm đến người bệnh.",
    created: "2025-07-20T09:29:00Z",
  },
  {
    id: "159",
    name: "Lương Thị I",
    phone: "0912345836",
    email: "luong.thi.i@example.com",
    review: "Khám rồi vẫn không biết bệnh gì, không yên tâm chút nào.",
    created: "2025-07-21T12:46:00Z",
  },
  {
    id: "160",
    name: "Vũ Văn J",
    phone: "0912345837",
    email: "vu.văn.j@example.com",
    review: "Máy móc trục trặc, phải đợi sửa rất lâu mới được tiếp tục khám.",
    created: "2025-07-22T15:03:00Z",
  },
  {
    id: "161",
    name: "Nguyễn Văn K",
    phone: "0912345838",
    email: "nguyễn.văn.k@example.com",
    review: "Không có chỗ ngồi chờ, bệnh nhân phải đứng rất lâu.",
    created: "2025-07-23T08:20:00Z",
  },
  {
    id: "162",
    name: "Trịnh Thị L",
    phone: "0912345839",
    email: "trinh.thi.l@example.com",
    review: "Đăng ký online rồi mà vẫn phải chờ cả tiếng đồng hồ.",
    created: "2025-07-24T11:37:00Z",
  },
  {
    id: "163",
    name: "Lý Văn M",
    phone: "0912345840",
    email: "ly.văn.m@example.com",
    review: "Giá thuốc tại quầy cao hơn nhiều so với bên ngoài.",
    created: "2025-07-25T14:54:00Z",
  },
  {
    id: "164",
    name: "Đoàn Thị N",
    phone: "0912345841",
    email: "doan.thi.n@example.com",
    review: "Thái độ bác sĩ thiếu nhiệt tình, không trả lời câu hỏi rõ ràng.",
    created: "2025-07-26T17:11:00Z",
  },
  {
    id: "165",
    name: "Kiều Văn O",
    phone: "0912345842",
    email: "kiều.văn.o@example.com",
    review: "Hẹn tái khám nhưng đến nơi vẫn phải chờ lại từ đầu.",
    created: "2025-07-27T10:28:00Z",
  },
  {
    id: "166",
    name: "Bùi Thị P",
    phone: "0912345843",
    email: "bui.thi.p@example.com",
    review: "Nhân viên kỹ thuật làm việc chậm, thiếu trách nhiệm.",
    created: "2025-07-28T13:45:00Z",
  },
  {
    id: "167",
    name: "Tống Văn Q",
    phone: "0912345844",
    email: "tống.văn.q@example.com",
    review: "Không có người hướng dẫn trong khu vực khám, rất lộn xộn.",
    created: "2025-07-29T16:02:00Z",
  },
  {
    id: "168",
    name: "Phan Thị R",
    phone: "0912345845",
    email: "phan.thi.r@example.com",
    review: "Không khí phòng chờ quá nóng, không có điều hòa.",
    created: "2025-07-30T09:19:00Z",
  },
  {
    id: "169",
    name: "Nguyễn Văn S",
    phone: "0912345846",
    email: "nguyễn.văn.s@example.com",
    review: "Khâu thanh toán rườm rà, mất thời gian.",
    created: "2025-07-31T12:36:00Z",
  },
  {
    id: "170",
    name: "Võ Thị T",
    phone: "0912345847",
    email: "vo.thi.t@example.com",
    review: "Y tá gọi nhầm tên, gây nhầm lẫn giữa bệnh nhân.",
    created: "2025-08-01T15:53:00Z",
  },
  {
    id: "171",
    name: "Hồ Văn U",
    phone: "0912345848",
    email: "hồ.văn.u@example.com",
    review: "Quy trình xét nghiệm chậm, chờ kết quả quá lâu.",
    created: "2025-08-02T08:10:00Z",
  },
  {
    id: "172",
    name: "Trương Thị V",
    phone: "0912345849",
    email: "truong.thi.v@example.com",
    review: "Không có nơi để đồ cá nhân, rất bất tiện.",
    created: "2025-08-03T11:27:00Z",
  },
  {
    id: "173",
    name: "Đặng Văn W",
    phone: "0912345850",
    email: "dặng.văn.w@example.com",
    review:
      "Bác sĩ dùng từ chuyên môn quá nhiều, không giải thích cho người bệnh hiểu.",
    created: "2025-08-04T14:44:00Z",
  },
  {
    id: "174",
    name: "Cao Thị X",
    phone: "0912345851",
    email: "cao.thi.x@example.com",
    review: "Dịch vụ chăm sóc sau khám gần như không có.",
    created: "2025-08-05T17:01:00Z",
  },
  {
    id: "175",
    name: "Nguyễn Văn Y",
    phone: "0912345852",
    email: "nguyễn.văn.y@example.com",
    review: "Không hài lòng với cách xử lý phản ánh của bệnh viện.",
    created: "2025-08-06T10:18:00Z",
  },
  {
    id: "176",
    name: "Nguyễn Thị A",
    phone: "0912345853",
    email: "nguyễn.thi.a@example.com",
    review: "Thái độ của nhân viên không thân thiện, trả lời cộc lốc.",
    created: "2025-08-07T13:35:00Z",
  },
  {
    id: "177",
    name: "Trần Văn B",
    phone: "0912345854",
    email: "trần.văn.b@example.com",
    review: "Chờ khám quá lâu, không có thông báo rõ ràng.",
    created: "2025-08-08T16:52:00Z",
  },
  {
    id: "178",
    name: "Lê Thị C",
    phone: "0912345855",
    email: "lê.thi.c@example.com",
    review: "Quy trình khám rườm rà, mất nhiều thời gian.",
    created: "2025-08-09T09:09:00Z",
  },
  {
    id: "179",
    name: "Phạm Văn D",
    phone: "0912345856",
    email: "pham.văn.d@example.com",
    review: "Bác sĩ khám rất sơ sài, không giải thích rõ tình trạng bệnh.",
    created: "2025-08-10T12:26:00Z",
  },
  {
    id: "180",
    name: "Hoàng Thị E",
    phone: "0912345857",
    email: "hoang.thi.e@example.com",
    review: "Phòng khám đông đúc, không đảm bảo vệ sinh.",
    created: "2025-08-11T15:43:00Z",
  },
  {
    id: "181",
    name: "Đỗ Văn F",
    phone: "0912345858",
    email: "dỗ.văn.f@example.com",
    review: "Chi phí cao nhưng chất lượng phục vụ không tương xứng.",
    created: "2025-08-12T08:00:00Z",
  },
  {
    id: "182",
    name: "Ngô Thị G",
    phone: "0912345859",
    email: "ngo.thi.g@example.com",
    review: "Lễ tân không hướng dẫn rõ ràng, gây khó khăn cho bệnh nhân mới.",
    created: "2025-08-13T11:17:00Z",
  },
  {
    id: "183",
    name: "Mai Văn H",
    phone: "0912345860",
    email: "mai.văn.h@example.com",
    review: "Bác sĩ khám qua loa, cảm giác không quan tâm đến người bệnh.",
    created: "2025-08-14T14:34:00Z",
  },
  {
    id: "184",
    name: "Lương Thị I",
    phone: "0912345861",
    email: "luong.thi.i@example.com",
    review: "Khám rồi vẫn không biết bệnh gì, không yên tâm chút nào.",
    created: "2025-08-15T17:51:00Z",
  },
  {
    id: "185",
    name: "Vũ Văn J",
    phone: "0912345862",
    email: "vu.văn.j@example.com",
    review: "Máy móc trục trặc, phải đợi sửa rất lâu mới được tiếp tục khám.",
    created: "2025-07-01T10:08:00Z",
  },
  {
    id: "186",
    name: "Nguyễn Văn K",
    phone: "0912345863",
    email: "nguyễn.văn.k@example.com",
    review: "Không có chỗ ngồi chờ, bệnh nhân phải đứng rất lâu.",
    created: "2025-07-02T13:25:00Z",
  },
  {
    id: "187",
    name: "Trịnh Thị L",
    phone: "0912345864",
    email: "trinh.thi.l@example.com",
    review: "Đăng ký online rồi mà vẫn phải chờ cả tiếng đồng hồ.",
    created: "2025-07-03T16:42:00Z",
  },
  {
    id: "188",
    name: "Lý Văn M",
    phone: "0912345865",
    email: "ly.văn.m@example.com",
    review: "Giá thuốc tại quầy cao hơn nhiều so với bên ngoài.",
    created: "2025-07-04T09:59:00Z",
  },
  {
    id: "189",
    name: "Đoàn Thị N",
    phone: "0912345866",
    email: "doan.thi.n@example.com",
    review: "Thái độ bác sĩ thiếu nhiệt tình, không trả lời câu hỏi rõ ràng.",
    created: "2025-07-05T12:16:00Z",
  },
  {
    id: "190",
    name: "Kiều Văn O",
    phone: "0912345867",
    email: "kiều.văn.o@example.com",
    review: "Hẹn tái khám nhưng đến nơi vẫn phải chờ lại từ đầu.",
    created: "2025-07-06T15:33:00Z",
  },
  {
    id: "191",
    name: "Bùi Thị P",
    phone: "0912345868",
    email: "bui.thi.p@example.com",
    review: "Nhân viên kỹ thuật làm việc chậm, thiếu trách nhiệm.",
    created: "2025-07-07T08:50:00Z",
  },
  {
    id: "192",
    name: "Tống Văn Q",
    phone: "0912345869",
    email: "tống.văn.q@example.com",
    review: "Không có người hướng dẫn trong khu vực khám, rất lộn xộn.",
    created: "2025-07-08T11:07:00Z",
  },
  {
    id: "193",
    name: "Phan Thị R",
    phone: "0912345870",
    email: "phan.thi.r@example.com",
    review: "Không khí phòng chờ quá nóng, không có điều hòa.",
    created: "2025-07-09T14:24:00Z",
  },
  {
    id: "194",
    name: "Nguyễn Văn S",
    phone: "0912345871",
    email: "nguyễn.văn.s@example.com",
    review: "Khâu thanh toán rườm rà, mất thời gian.",
    created: "2025-07-10T17:41:00Z",
  },
  {
    id: "195",
    name: "Võ Thị T",
    phone: "0912345872",
    email: "vo.thi.t@example.com",
    review: "Y tá gọi nhầm tên, gây nhầm lẫn giữa bệnh nhân.",
    created: "2025-07-11T10:58:00Z",
  },
  {
    id: "196",
    name: "Hồ Văn U",
    phone: "0912345873",
    email: "hồ.văn.u@example.com",
    review: "Quy trình xét nghiệm chậm, chờ kết quả quá lâu.",
    created: "2025-07-12T13:15:00Z",
  },
  {
    id: "197",
    name: "Trương Thị V",
    phone: "0912345874",
    email: "truong.thi.v@example.com",
    review: "Không có nơi để đồ cá nhân, rất bất tiện.",
    created: "2025-07-13T16:32:00Z",
  },
  {
    id: "198",
    name: "Đặng Văn W",
    phone: "0912345875",
    email: "dặng.văn.w@example.com",
    review:
      "Bác sĩ dùng từ chuyên môn quá nhiều, không giải thích cho người bệnh hiểu.",
    created: "2025-07-14T09:49:00Z",
  },
  {
    id: "199",
    name: "Cao Thị X",
    phone: "0912345876",
    email: "cao.thi.x@example.com",
    review: "Dịch vụ chăm sóc sau khám gần như không có.",
    created: "2025-07-15T12:06:00Z",
  },
  {
    id: "200",
    name: "Nguyễn Văn Y",
    phone: "0912345877",
    email: "nguyễn.văn.y@example.com",
    review: "Không hài lòng với cách xử lý phản ánh của bệnh viện.",
    created: "2025-07-16T15:23:00Z",
  },
];

export const dataReviews = reviews.sort(
  (a, b) => new Date(b.created).getTime() - new Date(a.created).getTime()
);

export const dataCategoryNews: CategoryNewsEntity[] = [
  { id: 1, name: "Hoạt động bệnh viện" },
  { id: 2, name: "Chăm sóc sức khỏe" },
  { id: 3, name: "Nghiên cứu y học" },
  { id: 4, name: "Câu chuyện bệnh nhân" },
  { id: 5, name: "Thông báo" },
];

export const dataNews: NewsEntity[] = [
  // Hoạt động bệnh viện (id = 1)
  {
    id: 101,
    title: "Bệnh viện khai trương khoa Nội tổng hợp mới",
    description:
      "Khoa Nội tổng hợp mới được trang bị hiện đại, phục vụ tốt hơn nhu cầu khám chữa bệnh.",
    image: "https://picsum.photos/400/200?random=1",
    category: "1",
  },
  {
    id: 102,
    title: "Khởi động chương trình khám sức khỏe miễn phí cho người cao tuổi",
    description:
      "Bệnh viện tổ chức chuỗi sự kiện khám sức khỏe miễn phí cho người già trên 60 tuổi.",
    image: "https://picsum.photos/400/200?random=2",
    category: "1",
  },
  {
    id: 103,
    title: "Hội thảo nội bộ về cải tiến chất lượng dịch vụ",
    description:
      "Các y bác sĩ cùng nhau chia sẻ kinh nghiệm và ý tưởng nhằm nâng cao chất lượng chăm sóc bệnh nhân.",
    image: "https://picsum.photos/400/200?random=3",
    category: "1",
  },
  {
    id: 104,
    title: "Tặng quà cho bệnh nhân nghèo nhân dịp lễ lớn",
    description:
      "Hơn 200 phần quà đã được trao tặng cho bệnh nhân có hoàn cảnh khó khăn.",
    image: "https://picsum.photos/400/200?random=4",
    category: "1",
  },
  {
    id: 105,
    title: "Khánh thành khu vực tiếp đón mới",
    description:
      "Khu vực tiếp đón hiện đại, rộng rãi và tiện nghi được đưa vào sử dụng.",
    image: "https://picsum.photos/400/200?random=5",
    category: "1",
  },
  {
    id: 106,
    title: "Bệnh viện triển khai dịch vụ đăng ký khám trực tuyến",
    description:
      "Người dân có thể đặt lịch khám qua website, tiết kiệm thời gian chờ đợi.",
    image: "https://picsum.photos/400/200?random=26",
    category: "1",
  },
  {
    id: 107,
    title: "Bệnh viện hợp tác với trường đại học y dược",
    description:
      "Ký kết hợp tác đào tạo bác sĩ và nghiên cứu y khoa chuyên sâu.",
    image: "https://picsum.photos/400/200?random=27",
    category: "1",
  },
  {
    id: 108,
    title: "Tổ chức ngày hội hiến máu tình nguyện",
    description:
      "Hàng trăm cán bộ nhân viên và người dân đã tham gia hiến máu.",
    image: "https://picsum.photos/400/200?random=28",
    category: "1",
  },
  {
    id: 109,
    title: "Bệnh viện đưa vào sử dụng hệ thống xét nghiệm tự động",
    description:
      "Rút ngắn thời gian trả kết quả và tăng độ chính xác cho bệnh nhân.",
    image: "https://picsum.photos/400/200?random=29",
    category: "1",
  },
  {
    id: 110,
    title: "Khởi công xây dựng khu điều trị nội trú mới",
    description:
      "Dự án mở rộng bệnh viện nhằm nâng cao chất lượng chăm sóc bệnh nhân.",
    image: "https://picsum.photos/400/200?random=30",
    category: "1",
  },

  // Chăm sóc sức khỏe (id = 2)
  {
    id: 201,
    title: "10 thói quen tốt để bảo vệ tim mạch",
    description:
      "Chia sẻ những thói quen lành mạnh giúp phòng ngừa các bệnh tim mạch.",
    image: "https://picsum.photos/400/200?random=6",
    category: "2",
  },
  {
    id: 202,
    title: "Lợi ích của việc tập thể dục buổi sáng",
    description:
      "Tập thể dục sáng giúp tăng cường sức khỏe và tinh thần minh mẫn.",
    image: "https://picsum.photos/400/200?random=7",
    category: "2",
  },
  {
    id: 203,
    title: "Chế độ ăn uống khoa học cho người tiểu đường",
    description:
      "Hướng dẫn chế độ dinh dưỡng phù hợp để kiểm soát đường huyết.",
    image: "https://picsum.photos/400/200?random=8",
    category: "2",
  },
  {
    id: 204,
    title: "Cách giảm stress hiệu quả tại nhà",
    description:
      "Một số bài tập đơn giản giúp giảm căng thẳng và cải thiện tinh thần.",
    image: "https://picsum.photos/400/200?random=9",
    category: "2",
  },
  {
    id: 205,
    title: "Ngủ đủ giấc và tác động đến sức khỏe",
    description:
      "Ngủ đủ 7-8 tiếng mỗi ngày giúp tăng cường hệ miễn dịch và trí nhớ.",
    image: "https://picsum.photos/400/200?random=10",
    category: "2",
  },
  {
    id: 206,
    title: "Tác dụng của việc uống đủ nước mỗi ngày",
    description: "Uống đủ nước giúp cải thiện chức năng thận và làm đẹp da.",
    image: "https://picsum.photos/400/200?random=31",
    category: "2",
  },
  {
    id: 207,
    title: "Lợi ích của yoga đối với tinh thần",
    description: "Yoga giúp giảm lo âu, căng thẳng và cải thiện sự tập trung.",
    image: "https://picsum.photos/400/200?random=32",
    category: "2",
  },
  {
    id: 208,
    title: "Dinh dưỡng cho phụ nữ mang thai",
    description:
      "Cung cấp các nhóm thực phẩm cần thiết cho mẹ và bé phát triển khỏe mạnh.",
    image: "https://picsum.photos/400/200?random=33",
    category: "2",
  },
  {
    id: 209,
    title: "Đi bộ 30 phút mỗi ngày có lợi ích gì?",
    description:
      "Đi bộ thường xuyên giúp cải thiện hệ tim mạch và giảm nguy cơ béo phì.",
    image: "https://picsum.photos/400/200?random=34",
    category: "2",
  },
  {
    id: 210,
    title: "Cách bảo vệ mắt khi dùng máy tính nhiều",
    description: "Nên nghỉ mắt 5 phút sau mỗi 30 phút làm việc với màn hình.",
    image: "https://picsum.photos/400/200?random=35",
    category: "2",
  },

  // Nghiên cứu y học (id = 3)
  {
    id: 301,
    title: "Công bố nghiên cứu mới về ung thư phổi",
    description:
      "Các nhà khoa học phát hiện phương pháp điều trị tiềm năng cho bệnh nhân ung thư phổi.",
    image: "https://picsum.photos/400/200?random=11",
    category: "3",
  },
  {
    id: 302,
    title: "Ứng dụng AI trong chẩn đoán bệnh sớm",
    description:
      "Trí tuệ nhân tạo đang được nghiên cứu để hỗ trợ bác sĩ trong chẩn đoán.",
    image: "https://picsum.photos/400/200?random=12",
    category: "3",
  },
  {
    id: 303,
    title: "Thử nghiệm vaccine mới chống cúm mùa",
    description:
      "Các nhà khoa học đang thử nghiệm vaccine với hiệu quả cao hơn và ít tác dụng phụ.",
    image: "https://picsum.photos/400/200?random=13",
    category: "3",
  },
  {
    id: 304,
    title: "Nghiên cứu gene trong điều trị bệnh hiếm",
    description:
      "Liệu pháp gene mở ra hi vọng mới cho các bệnh nhân mắc bệnh di truyền.",
    image: "https://picsum.photos/400/200?random=14",
    category: "3",
  },
  {
    id: 305,
    title: "Công bố kết quả nghiên cứu về sức khỏe tâm thần",
    description:
      "Nghiên cứu mới chỉ ra mối liên hệ giữa chế độ ăn uống và sức khỏe tâm thần.",
    image: "https://picsum.photos/400/200?random=15",
    category: "3",
  },
  {
    id: 306,
    title: "Thử nghiệm thuốc mới điều trị Alzheimer",
    description:
      "Thuốc đang trong giai đoạn thử nghiệm lâm sàng cho kết quả khả quan.",
    image: "https://picsum.photos/400/200?random=36",
    category: "3",
  },
  {
    id: 307,
    title: "Nghiên cứu tế bào gốc trong điều trị tiểu đường",
    description:
      "Liệu pháp tế bào gốc có tiềm năng giúp kiểm soát đường huyết.",
    image: "https://picsum.photos/400/200?random=37",
    category: "3",
  },
  {
    id: 308,
    title: "AI hỗ trợ dự đoán nguy cơ mắc bệnh tim",
    description:
      "Ứng dụng AI phân tích dữ liệu sức khỏe để dự đoán nguy cơ bệnh tim mạch.",
    image: "https://picsum.photos/400/200?random=38",
    category: "3",
  },
  {
    id: 309,
    title: "Khám phá cơ chế lây lan của virus mới",
    description:
      "Nghiên cứu cơ chế giúp đưa ra phương pháp phòng chống hiệu quả hơn.",
    image: "https://picsum.photos/400/200?random=39",
    category: "3",
  },
  {
    id: 310,
    title: "Ứng dụng công nghệ nano trong y học",
    description:
      "Công nghệ nano mở ra nhiều giải pháp mới trong điều trị và chẩn đoán.",
    image: "https://picsum.photos/400/200?random=40",
    category: "3",
  },

  // Câu chuyện bệnh nhân (id = 4)
  {
    id: 401,
    title: "Hành trình hồi phục kỳ diệu của bệnh nhân ung thư",
    description:
      "Một bệnh nhân chia sẻ câu chuyện vượt qua bệnh ung thư sau nhiều tháng điều trị.",
    image: "https://picsum.photos/400/200?random=16",
    category: "4",
  },
  {
    id: 402,
    title: "Bé gái 5 tuổi vượt qua căn bệnh tim bẩm sinh",
    description:
      "Câu chuyện đầy xúc động về sự hồi phục của một bệnh nhi sau ca phẫu thuật tim.",
    image: "https://picsum.photos/400/200?random=17",
    category: "4",
  },
  {
    id: 403,
    title: "Người mẹ hiến gan cứu con",
    description: "Một ca ghép gan thành công nhờ tình mẫu tử thiêng liêng.",
    image: "https://picsum.photos/400/200?random=18",
    category: "4",
  },
  {
    id: 404,
    title: "Bệnh nhân phục hồi sau tai nạn giao thông nghiêm trọng",
    description:
      "Câu chuyện về sự kiên cường và nỗ lực phục hồi của bệnh nhân.",
    image: "https://picsum.photos/400/200?random=19",
    category: "4",
  },
  {
    id: 405,
    title: "Niềm vui của bệnh nhân được ghép thận thành công",
    description: "Một bệnh nhân đã có cơ hội sống mới sau ca ghép thận.",
    image: "https://picsum.photos/400/200?random=20",
    category: "4",
  },
  {
    id: 406,
    title: "Bệnh nhân vượt qua hôn mê kéo dài",
    description:
      "Sau nhiều tháng hôn mê, bệnh nhân đã tỉnh lại và dần hồi phục.",
    image: "https://picsum.photos/400/200?random=41",
    category: "4",
  },
  {
    id: 407,
    title: "Người đàn ông hồi phục sau ca ghép tim",
    description:
      "Một ca phẫu thuật ghép tim thành công đã đem lại sự sống mới.",
    image: "https://picsum.photos/400/200?random=42",
    category: "4",
  },
  {
    id: 408,
    title: "Bệnh nhân vượt qua căn bệnh hiếm gặp",
    description: "Câu chuyện đầy nghị lực của một bệnh nhân mắc bệnh hiếm.",
    image: "https://picsum.photos/400/200?random=43",
    category: "4",
  },
  {
    id: 409,
    title: "Người lính hồi phục sau chiến tranh",
    description:
      "Một thương binh đã hồi phục và trở lại cuộc sống bình thường.",
    image: "https://picsum.photos/400/200?random=44",
    category: "4",
  },
  {
    id: 410,
    title: "Bệnh nhân được hồi sinh sau ngừng tim",
    description: "Nhờ sự can thiệp kịp thời, bệnh nhân đã qua cơn nguy kịch.",
    image: "https://picsum.photos/400/200?random=45",
    category: "4",
  },

  // Thông báo (id = 5)
  {
    id: 501,
    title: "Lịch nghỉ lễ Quốc khánh",
    description:
      "Bệnh viện thông báo lịch nghỉ lễ 2/9 cho toàn thể cán bộ và bệnh nhân.",
    image: "https://picsum.photos/400/200?random=21",
    category: "5",
  },
  {
    id: 502,
    title: "Cập nhật quy trình tiếp nhận bệnh nhân",
    description:
      "Thông báo thay đổi trong quy trình tiếp nhận và phân loại bệnh nhân.",
    image: "https://picsum.photos/400/200?random=22",
    category: "5",
  },
  {
    id: 503,
    title: "Thông báo về phí dịch vụ khám chữa bệnh",
    description:
      "Một số dịch vụ y tế sẽ được điều chỉnh mức phí kể từ tháng tới.",
    image: "https://picsum.photos/400/200?random=23",
    category: "5",
  },
  {
    id: 504,
    title: "Mở rộng thời gian làm việc của phòng khám",
    description:
      "Phòng khám sẽ mở cửa thêm vào buổi tối để phục vụ bệnh nhân tốt hơn.",
    image: "https://picsum.photos/400/200?random=24",
    category: "5",
  },
  {
    id: 505,
    title: "Thông báo tuyển dụng nhân sự mới",
    description:
      "Bệnh viện cần tuyển thêm điều dưỡng và bác sĩ cho nhiều khoa.",
    image: "https://picsum.photos/400/200?random=25",
    category: "5",
  },
  {
    id: 506,
    title: "Thông báo thay đổi giờ làm việc",
    description:
      "Một số khoa sẽ có sự điều chỉnh về giờ khám bệnh từ tuần tới.",
    image: "https://picsum.photos/400/200?random=46",
    category: "5",
  },
  {
    id: 507,
    title: "Cảnh báo dịch bệnh theo mùa",
    description: "Khuyến cáo người dân tiêm vaccine phòng bệnh đúng lịch.",
    image: "https://picsum.photos/400/200?random=47",
    category: "5",
  },
  {
    id: 508,
    title: "Thông báo bảo trì hệ thống điện",
    description: "Một số khu vực sẽ tạm ngừng cấp điện để bảo trì thiết bị.",
    image: "https://picsum.photos/400/200?random=48",
    category: "5",
  },
  {
    id: 509,
    title: "Thông báo cập nhật phần mềm bệnh án điện tử",
    description:
      "Hệ thống sẽ được nâng cấp để phục vụ tốt hơn cho bác sĩ và bệnh nhân.",
    image: "https://picsum.photos/400/200?random=49",
    category: "5",
  },
  {
    id: 510,
    title: "Thông báo hội nghị cán bộ nhân viên",
    description:
      "Bệnh viện tổ chức hội nghị tổng kết cuối năm cho toàn thể nhân viên.",
    image: "https://picsum.photos/400/200?random=50",
    category: "5",
  },
];

export const contentTemplate = `
  <!-- Ảnh chính (giữ nguyên nếu vẫn OK) -->
  <img src="https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=1200"
       alt="Trung tâm"
       loading="lazy"
       style="width:100%; border-radius:12px; margin:20px 0;" />

  <p>Sáng ngày 27/08/2025, Bệnh viện Đa khoa Trung ương đã chính thức đưa vào hoạt động Trung tâm Khám chữa bệnh chất lượng cao...</p>

  <!-- Cụm 2 ảnh thay bằng public link ổn định -->
  <div style="display:grid; grid-template-columns:1fr 1fr; gap:16px; margin:20px 0;">
    <img src="https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=1200"
       alt="Trung tâm"
       loading="lazy"
       style="width:100%; border-radius:12px; margin:20px 0;" />
    <img src="https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=1200"
       alt="Trung tâm"
       loading="lazy"
       style="width:100%; border-radius:12px; margin:20px 0;" />
  </div>

  <p>Trung tâm được trang bị nhiều thiết bị y tế hiện đại, đạt chuẩn quốc tế...</p>

  <!-- Ảnh cuối thay bằng public link ổn định -->
  <img src="https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=1200"
       alt="Trung tâm"
       loading="lazy"
       style="width:100%; border-radius:12px; margin:20px 0;" />

  <p>Với sự kiện khai trương này, Bệnh viện Đa khoa Trung ương khẳng định cam kết mang lại dịch vụ khám chữa bệnh chất lượng cao...</p>
`;
